### ISSUE TITLE
Manual values not stored correctly if switch to Auto and then to Manual.

### ISSUE THREAD

**Issue by 10MDS** [jareff-g/ALT-Scann8#134]
There is an inconsistency to point out:
I was very pleased to notice that if I activate autowhite I see in the values fields, the values it is processing automatically, and if I deactivate it, it returns to the manual values I had previously.

So far, so good, but...
if in the beginning I use manual value, both of Exposition and/or White Balance, and then activate AutoWhite and then go back to manual Exposition and/or White Balance, even if I see the original manual values again, if I close ALT-Scann, and then I reopen it and I accept to load the previous settings, the manual values results setted on the values it was using when "Auto" was, active, even though when I closed the interface, the AutoWhite or Auto Exposure where deactivated.
Only the values are wrong, the "Auto" button resuts correctly turned off.
Therefore, the last manual values are not stored correctly if I switch to Auto and then again to Manual.

Mariano

**Comment by jareff-g** [comment]
A fix has been done to handle this case, will be available in next releas.

**Comment by jareff-g** [comment]
Fix available in version 1.10.45. Please close if it works for you.

**Comment by jareff-g** [comment]
In last version (1.10.53) manual exposure is correctly restored at the camera when disabling AE.
