### ISSUE TITLE
Starting up version 1.10.53 gives "Qr import issue"

### ISSUE THREAD

**Issue by ToRa-51** [jareff-g/ALT-Scann8#149]
Juan,

Yesterday I already tested version 1.10.53. Everything worked fine, but today after booting on the command line I saw the error message listed in the title.
After a while of Google I had found it, the qrcode library was not loaded. Then entered "sudo apt-get install python3-qrcode" and then restarted the app. The error message was gone and the screen now has a frame with Debug info and a QR code under the Brightness/Contrast frame.

I think install command should now be added to Wiki -> Frequently Asked Questions -> Question 1.

Ton.

**Comment by jareff-g** [comment]
Hello Ton,
You are right. I added it in the 'Recent changes' page of the Wiki, but I can add it as well in the FAQ.
Rgds/Juan

**Comment by jareff-g** [comment]
Added to the FAQ
